やっぱオプションに戻した

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -278,7 +278,7 @@ dotfiles_logo="
   *** WHAT IS INSIDE? ***
   1. Download https://github.com/Alfr0475/dotfiles.git
   2. Symlinking dot files to your home directory
-  3. Execute all sh files within \`etc/init/\`
+  3. Execute all sh files within \`etc/init/\` (optional)
 
   See the README for documentation.
   https://github.com/Alfr0475/dotfiles
@@ -343,21 +343,23 @@ function dotfiles_deploy() {
 }
 
 function dotfiles_initialize() {
-    e_newline
-    e_header "Initializing dotfiles..."
+    if [ "$1" = "init" ]; then
+        e_newline
+        e_header "Initializing dotfiles..."
 
-    if is_debug; then
-        :
-    else
-        if [ -f Makefile ]; then
-            make init
+        if is_debug; then
+            :
         else
-            log_fail "Makefile: not found"
-            exit 1
-        fi
-    fi &&
+            if [ -f Makefile ]; then
+                make init
+            else
+                log_fail "Makefile: not found"
+                exit 1
+            fi
+        fi &&
 
-        e_newline && e_done "Initialize"
+            e_newline && e_done "Initialize"
+    fi
 }
 
 function dotfiles_install() {
@@ -370,7 +372,7 @@ function dotfiles_install() {
     dotfiles_deploy &&
 
     # 3. Execute all sh files within etc/init/
-    dotfiles_initialize
+    dotfiles_initialize "$@"
 }
 
 if echo "$-" | grep -q "i"; then
@@ -395,7 +397,7 @@ else
 
         trap "e_error 'terminated'; exit 1" INT ERR
         echo "$dotfiles_logo"
-        dotfiles_install
+        dotfiles_install "$@"
 
         if [ -p /dev/stdin ]; then
             e_warning "Now continue with Rebooting your shell"
